### ISSUE TITLE
status of the euro modules?

### ISSUE THREAD

**Issue by KeLaiFu** [thismatters/EurorackLfo#1]
I've been meaning to ask this for a long time, not sure if I asked and then forgot about it so apologies if you've already answered on another repo...but...
Would it be possible to add a status on the repos so we know which ones are ready to be fabricated? 
I'm keen to built the yusynth LFO and a few of the others, so would appreciate conformation it should work once its built and problems I may have are down to my shonky soldering.

Cheers

**Comment by thismatters** [comment]
Absolutely! I've been going back through the individual repos and updating the "Vendors" section to link boards that work without having to do any hacking, but I'm a little behind. I've been considering adding a top level repo for which each eurorack module would be (appropriately) a git submodule, but I haven't gotten to it yet.

**Comment by thismatters** [comment]
The [VCO circuit](https://github.com/thismatters/EurorackVco) has a link to OSHPark to get PCBs made. I will probably be revising that soon because some aspects are not perfectly functional (PWM range is kinda broken, sine shape could be better), but overall it works.

**Comment by KeLaiFu** [comment]
fantastic! watching those 1U modules too, I have a lot of 1U space to fill.

**Comment by thismatters** [comment]
Alright. I went through and updated all the repos for which prototypes have been made. Only one circuit is cursed right now (so don't build the mult... how I messed up the simplest possible module is beyond me, but I managed it :).

Also I added [this new status repo](https://github.com/thismatters/Eurorack) so you can get an birds-eye view of the project.
